name: Slack Notify

on:
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Slack
        env:
          HOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          echo "🔍 Testing if HOOK_URL is loaded..."
          if [ -z "$HOOK_URL" ]; then
            echo "::error::SLACK_WEBHOOK_URL secret is missing or not accessible"
            exit 1
          fi

          curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"ACC GitHub Actions 실습: Slack 연결 성공!"}' \
            "$HOOK_URL"
